version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: ./docker/java/Dockerfile
    container_name: app
    ports:
      - "8001:8001"
    volumes:
      - ./:/app
    command: ./mvnw spring-boot:run -Dspring-boot.run.profiles=mysql -Dspring-boot.run.jvmArguments="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000"

  mysql:
    image: mysql:8.0.23
    container_name: mysql
    ports:
      - "3333:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_DATABASE=demo
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d

  redis:
    image: redis:6.0-alpine
    container_name: redis
    hostname: redis
    restart: always
    ports:
      - "6340:6379"
    volumes:
      - ./docker/redis/redis.conf:/usr/local/etc/redis/redis.conf

volumes:
  mysql_data:
  mysql_config: